import { CrisisPreset } from '../types';

export const CRISIS_PRESETS: CrisisPreset[] = [
  {
    id: 'trishuli-bhotekoshi-2026',
    name: 'August 2026 Trishuli Flood (Bhote Koshi)',
    nepaliName: 'त्रिशूली तथा भोटेकोशी भीषण बाढी (साउन २०८३)',
    country: 'Nepal',
    region: 'Bahrabise & Upper Bhote Koshi / Trishuli Corridor',
    description: 'Mandatory Hackathon Case Study: Massive monsoon river surge & landslide dam burst along the Bhote Koshi / Trishuli corridor, severing Arniko Highway bridges and cutting off Bahrabise, Larcha, and border settlements.',
    preDate: '2026-07-28',
    postDate: '2026-08-14',
    bbox: {
      north: 27.95,
      south: 27.70,
      east: 86.02,
      west: 85.82,
    },
    center: [27.795, 85.905],
    zoom: 12,
  },
  {
    id: 'melamchi-2021',
    name: 'Melamchi Valley Disaster (2021)',
    nepaliName: 'मेलम्ची बाढी तथा गेग्रान पहिरो (२०७८)',
    country: 'Nepal',
    region: 'Sindhupalchok, Bagmati Province',
    description: 'Catastrophic glacial/moraine dam breach & debris flow carrying 4-12m sediment down Melamchi riverbed, severing 4 key bridges and trapping upper Helambu settlements.',
    preDate: '2021-06-08',
    postDate: '2021-06-16',
    bbox: {
      north: 28.05,
      south: 27.80,
      east: 85.65,
      west: 85.50,
    },
    center: [27.935, 85.575],
    zoom: 12,
  },
  {
    id: 'koshi-river-flood',
    name: 'Koshi Basin Embankment Breach',
    nepaliName: 'सप्तकोशी नदी बाँध फुटेको बाढी',
    country: 'Nepal',
    region: 'Sunsari / Saptari, Koshi Province',
    description: 'Massive eastern terai river diversion submerging agricultural plains, cutting north-south highways, and stranding thousands across rural embankment settlements.',
    preDate: '2022-07-14',
    postDate: '2022-07-28',
    bbox: {
      north: 26.65,
      south: 26.45,
      east: 87.15,
      west: 86.95,
    },
    center: [26.55, 87.05],
    zoom: 12,
  },
  {
    id: 'kathmandu-valley-2024',
    name: 'Kathmandu Valley Flash Floods (2024)',
    nepaliName: 'काठमाडौं उपत्यका बाढी (२०८१)',
    country: 'Nepal',
    region: 'Bagmati & Nakkhu Corridors, Central Nepal',
    description: 'Record torrential monsoon rainfall overflowing Bagmati, Hanumante, and Nakkhu riverbanks, isolating low-lying urban settlements and submerging transit corridors.',
    preDate: '2024-09-20',
    postDate: '2024-09-29',
    bbox: {
      north: 27.72,
      south: 27.64,
      east: 85.38,
      west: 85.27,
    },
    center: [27.68, 85.32],
    zoom: 13,
  },
];
